// Generated by ts-to-zod
import { z } from 'zod'

export const variableSchema = z.object({
    name: z.string(),
    example: z.string().optional(),
    max_length: z.number().optional(),
    type: z.union([z.literal('string'), z.literal('number'), z.literal('boolean')]).optional(),
})

export const settingsSchema = z.object({
    max_tokens: z.number().optional(),
    temperature: z.number().optional(),
    frequency_penalty: z.number().optional(),
    presence_penalty: z.number().optional(),
    stop: z.array(z.string()).optional(),
})

export const promptSchema = z.object({
    name: z.string(),
    description: z.string().optional(),
    tags: z.array(z.string()).optional(),
    engine: z.string(),
    prompt: z.string(),
    vars: z.record(variableSchema),
    settings: settingsSchema,
})
